from enum import Enum as PyEnum


class TipoEvento(str, PyEnum):
    RUPTURA = "RUPTURA"
    ATENUACAO = "ATENUAÇÃO"
    INDISPONIBILIDADE = "INDISPONIBILIDADE"
    SATURACAO = "SATURAÇÃO"
    TAXA_ERRO = "TAXA DE ERRO"
    OSCILACAO = "OSCILAÇÃO"
    FALHA_ELETRICA = "FALHA ELÉTRICA"
    OUTRAS = "OUTRAS"


TIPO_EVENTO_CHOICES = [(e.value, e.name.capitalize()) for e in TipoEvento]

SIGLAS_EVENTOS = {
    TipoEvento.RUPTURA.value: "RUP",
    TipoEvento.ATENUACAO.value: "ATN",
    TipoEvento.INDISPONIBILIDADE.value: "IND",
    TipoEvento.SATURACAO.value: "SAT",
    TipoEvento.TAXA_ERRO.value: "TXE",
    TipoEvento.OSCILACAO.value: "OSC",
    TipoEvento.FALHA_ELETRICA.value: "RGE",
    TipoEvento.OUTRAS.value: "OUT",
}


class TipoRede(str, PyEnum):
    METRO = "METRO"
    DWDM = "DWDM"
    CAPACIDADE = "CAPACIDADE"


TIPO_REDE_CHOICES = [(e.value, f"Rede {e.name.capitalize()}") for e in TipoRede]


class StatusAtendimento(int, PyEnum):
    PENDENTE_OS = 1
    AGUARDANDO_ANALISE = 2


STATUS_ATENDIMENTO_CHOICES = [
    (StatusAtendimento.PENDENTE_OS.value, "PENDENTE (Abertura de OS)"),
    (StatusAtendimento.AGUARDANDO_ANALISE.value, "AGUARDANDO ANALISE"),
]


class TipoAtendimento(int, PyEnum):
    NOC_TX = 660
    ATENUACAO_PARCEIRO = 661
    OSCILACAO_PARCEIRO = 662
    PT_NOC_CLIENTE = 663
    RUPTURA_PARCEIRO = 664
    ATENUACAO_MEGALINK = 666
    OSCILACAO_MEGALINK = 668
    ENERGIA = 723
    INDISPONIBILIDADE_SITE = 667
    REBOOT_SITE = 670
    OUTROS = 669
    RUPTURA_MEGALINK = 671
    LATENCIA_ALTA = 690
    DESTINO_INALCANCAVEL = 691
    ROTEAMENTO_INTERNO = 692
    SATURACAO_BACKBONE = 693
    INFRAESTRUTURA_VIRTUAL = 694
    MITIGACAO = 695
    NOC_IP_OUTROS = 696
    ACAO_TEMPORARIA_OSPF = 933
    ACAO_TEMPORARIA_MPLS = 934


TIPOS_ATENDIMENTO_CHOICES = [(t.value, t.name.replace("_", " ").title()) for t in TipoAtendimento]


class TipoAtendimentoSuporte(int, PyEnum):
    FTTH = 938
    FTTH_ATENUACAO_CTO = 939
    FTTH_ROTA_ATENUADA = 940
    FTTH_RUPTURA = 941
    FTTH_OLT_INDISPONIVEL = 942
    FTTH_SITE_INDISPONIVEL = 943
    FTTH_CTO_SEM_SINAL = 946
    FTTH_OUTROS = 947
    FTTH_AMPLIACAO_CTO = 957
    FTTH_CONCENTRADOR_INDISP = 958
    FTTH_CGNAT_INDISP = 959


TIPOS_ATENDIMENTO_SUPORTE_CHOICES = [(t.value, t.name.replace("_", " ").title()) for t in TipoAtendimentoSuporte]


class StatusSuporte(int, PyEnum):
    PENDENTE = 1
    AGUARDANDO_ANALISE = 2
    EM_ANDAMENTO = 22
    RESOLVIDO = 3
    FECHADO = 4


STATUS_SUPORTE_CHOICES = [
    (StatusSuporte.PENDENTE.value, "PENDENTE (Abertura de OS)"),
    (StatusSuporte.AGUARDANDO_ANALISE.value, "AGUARDANDO ANALISE"),
]


class TipoOS(int, PyEnum):
    DESLOCAMENTO_AVARIA = 616
    RUPTURA = 617
    ACESSO_SITE = 618
    VISTORIA_FERRAMENTA = 619
    INSTALACAO = 620
    REATIVACAO = 621
    RETIRADA_EQUIP = 622
    ACOMP_TROCA_POSTE = 623
    ATENUACAO_CTO = 624
    PREPARACAO_FIBRA = 625
    ENTREGA_SWAP = 626
    VAREJO_DEDICADO = 627
    CONJUNTA = 628
    SWAP_RUPTURA = 629
    VISTORIA_GERADOR = 630
    DESLOCAMENTO = 631
    LEVANTAMENTO_FONTES = 632
    SWAP_ATENUACAO = 633
    CTO_SEM_SINAL = 634
    CLIENTE_CORP_TESTE = 635
    EQUALIZACAO_DWDM = 636
    CLIENTE_CORP_ATENUACAO = 637
    CLIENTE_CORP_DOWN = 638
    CLIENTE_ISP_ATENUACAO = 639
    CLIENTE_ISP_TESTE = 640
    ALERTA_ENERGIA = 641
    CLIENTE_ISP_DOWN = 642
    AMPLIACAO_CTO = 643
    IMPLANTACAO_CTO = 644
    INDISPONIBILIDADE_SITE = 645
    INSTALACAO_CAMERAS = 646
    LEVANTAMENTO_CABOS = 647
    MANUTENCAO_POP = 648
    ATENUACAO_FIBRA = 649
    SITE_REINICIANDO = 650
    CTO_ATENUADA = 655
    CTO_SEM_SINAL_OS = 656
    ROTA_ATENUADA = 671
    OLT_INDISPONIVEL = 672
    CGNAT_INDISPONIVEL = 673
    CONCENTRADOR_INDISP = 674
    VERIFICACAO_TEMPERATURA = 682
    TROCA_MODULO = 683
    CORRECAO_EQUIP = 684
    LEITURA_FIBRA = 685
    MANUTENCAO_TRECHO = 689


TIPO_OS_CHOICES = [(t.value, t.name.replace("_", " ").title()) for t in TipoOS]
